spring:
  config:
    import: optional:file:env/.env.local[.properties]

  datasource:
    batch:
      url: ${BATCH_DATABASE_URL}
      username: ${BATCH_DATABASE_USERNAME}
      password: ${BATCH_DATABASE_PASSWORD}
      driver-class-name: ${BATCH_DATABASE_DRIVER}

    band:
      url: ${BAND_DATABASE_URL}
      username: ${BAND_DATABASE_USERNAME}
      password: ${BAND_DATABASE_PASSWORD}
      driver-class-name: ${BAND_DATABASE_DRIVER}

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
